name: flex_map_env
channels:
  - conda-forge
dependencies:
  - python=3.11
  - ipykernel
  - ipython
  - jupyter
  - nbconvert
  - pandoc
  - tectonic
  - texlive-core
  - make
  - numpy
  - pandas
  - requests
  - tqdm
  - networkx
  - rdflib
  - matplotlib
  - ipywidgets
  - pyyaml
  - weasyprint
  - pip
  - pip:
    - markdown
    
